apiVersion: v1
kind: Service
metadata:
    name: auth
    namespace: auth
    labels:
        app: auth
spec:
    selector:
        app: auth
    type: NodePort
    ports:
        - name: http
          port: 8000
          nodePort: 32043
        - name: http1
          port: 8001
          nodePort: 32044
